[plugin-info]
SHORT_PLUGIN_NAME = 'lecroy'

package-url = 'https://github.com/Attolab/pymodaq_plugins_lecroy'
description = 'PyMoDAQ plugin for Lecroy oscilloscopes (Waverunner).'

author = 'Constant Schouder'
author-email = 'constant.schouder@cea.fr'
license = 'MIT'

[plugin-install]
packages-required = ["pymodaq", "numpy", "easydict", "pyvisa", "pywin32","lecroydso"]
