[plugin-info]
SHORT_PLUGIN_NAME = 'lecroy'

package-url = 'https://github.com/Attolab/pymodaq_plugins_lecroy'
description = 'PyMoDAQ plugin for Lecroy oscilloscopes (Waverunner).'

author = 'David Bresteau'
author-email = 'david.bresteau@cea.fr'
license = 'MIT'

[plugin-install]
packages-required = ["pymodaq", "numpy", "easydict", "pyvisa", "pywin32"]
